[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "7fc2c61ce8285dba17e144cdee9876b5170f4370"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "af2b421a758f1c490fe09734c2e8d7a1101ecf6b9fad02f7b9334e0d6a9bc9e9"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.aarch64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "ffb8ca3fbc074488c6da65a661308c7e6495a172"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "aefc8b86317d97f2c3e15534acb3725ab2ef3446d2ecb02070c439944f649a04"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.aarch64-linux-musl.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d66d96cbddf7d233183c45b5805495ca70ce54c6"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "2c1d90ae5f72d716894c6f47e592729e136113f84c3747338fd3876f297860d9"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5acbea467e9ef3ab20181113143c8085d534666d"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "30103305918573d6a7ec5f3867ad244aa58b20d4695d11d1a31b50e881a190e3"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "fbc76f309d55606fbe5ac66407222edc9b7ea6ac"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "ab1d203b472b4246bcdc5478ad47868dc005b11aa3bec1c6e103c5129bed6736"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.i686-linux-gnu.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "22042b0736e363477f78efe68872d5def5acc959"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "2051f383fb932ebbe932f32713f51c3547b0c6e032c186db4648123c199b52f4"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.i686-linux-musl.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "9daf3288740c006935ab6530f14b2f9d6b31b3c7"
os = "windows"

    [[AzStorage.download]]
    sha256 = "1b82e50b198e9eda13a917a60f8f09c2f0dc9a9f430660998fb60a933e32d6ca"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.i686-w64-mingw32.tar.gz"
[[AzStorage]]
arch = "powerpc64le"
git-tree-sha1 = "561496027cbdc3f25a94e09e9aee1c3f56728ca8"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "4ea8daac62d17787235dc00b93d08ffef58c356be9d455e87e4fc65f3e8c8920"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "1ab88427dc7110b470e4632813f30e99745a5b52"
os = "macos"

    [[AzStorage.download]]
    sha256 = "e57f28f283218a790d8ced23be53ee8251ec8c746f73e9cff92343f4e4d99c67"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.x86_64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "a7640de6ad9e47b83a997166e730acf876b9cde7"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "011912727ad9db6c5180259cb75c40e6076a24a50b3dab3bbe76550f6b7afa96"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.x86_64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "1bf2153ac043cd29d3b3b6ddd092e0e138c2abd1"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "bc5ed5bd04b46630a49b0d745e7d210c410cc25bc907f076950282452094db7f"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.x86_64-linux-musl.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "a902c10ac6c2af997f5c5b56dcccf39678f50b18"
os = "freebsd"

    [[AzStorage.download]]
    sha256 = "1ce0d998a7386e943031af976b1df1a4215437abb2518a7c17d77cddc6535aa0"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "ba8c6e20d44873e6d2ec09a6d2dd69ffccc97fb4"
os = "windows"

    [[AzStorage.download]]
    sha256 = "f81152d618f9691f43060b700d7a5f722defd60c97e627f9fbbb8c079ff3f571"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+0/AzStorage.v0.2.0.x86_64-w64-mingw32.tar.gz"
