[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "f5af9159955e63fa74ccad1883ace6a5ebb1a33b"
os = "macos"

    [[AzStorage.download]]
    sha256 = "16ac4de1f77f75fd1f341d82705b0c960f28c607b6747b94c95504ba75dbae21"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.aarch64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "25f86d3c9c2dd72692d2608692e097e127d11637"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "18babf6ad6216db707678bc55dfd62a3b5f9d7f1f18be21ce4df1dd479064406"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.aarch64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "26d44dd0775ad9f2afceb147577f581ccd05c9ad"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "444abba8d716114e9655952f09a9db840cab910b19f3d0ceeb9877e5cdaaf03f"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.aarch64-linux-musl.tar.gz"
[[AzStorage]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6143b1cfa9669e4c529726a61e419f1346a7318"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "a95d93a1ccd2637de59daa24d349944f8dfb6c1e16d73b909dcbc7f8899fa354"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.armv6l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5a4e81a1b00d25640d388ab1793739bc37d984e5"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "19dcb00ca375620ec1c8e123958c8180487420a95a6be055cb36c157800ecf9f"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.armv6l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7cf2e6eded0fb80021738029e14990dc8238e2cc"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "397a26033bc5deace78421e96ba6490d74d323dfa487d663ede809abd010e486"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.armv7l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e3f865bce0fb147c53dcd387ca726de888ecd34a"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "4bce352901d3df51710ac481aef4d2e15e45f4473582497464b1d36023ccee20"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.armv7l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "de047b139fd4fe12961570892e789e6a31246f67"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "f7370c43f98d189efc09fff2e4d8d7c70a4296e1601b1ea7c5cd121e1ee04db2"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.i686-linux-gnu.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "70e2758f1b1e0b1996d99b36d25f9f6485c1b70a"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "269240a7848d5f90fdb0234f62a01953bea53c9794df77745a57c2fb825fa1d9"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.i686-linux-musl.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "eba293106ca1dccf597d4240e5c7e414f8deec2f"
os = "windows"

    [[AzStorage.download]]
    sha256 = "9ca83433f155b3bc1c376b616c8e9a02ff670a64f663bc3b338c73b19f549c39"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.i686-w64-mingw32.tar.gz"
[[AzStorage]]
arch = "powerpc64le"
git-tree-sha1 = "471cecb779cbd85621a5a8eb2bd1933bec8e8299"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "308b1d1f3560e1223312be8742e7760055426286e1e3326c31a632a92216608d"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.powerpc64le-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "92825cb2f46ad5d0a59bf534a12323e2bdd23dd6"
os = "macos"

    [[AzStorage.download]]
    sha256 = "904708655959f8dcedeebe1bfb3261a18f5caac1676fb3007e99239e3e2c85dd"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.x86_64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "0e6e37b577d0837865e0611223bdb48a0f4ef035"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "259893070daec36157fa30ad54c5179ff1a4f503cc532922b121b008dcc038d5"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.x86_64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "7a206ebeb21d969247e184304ed11e0e00e23cf5"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "b4c44a5d0e91350224b3234b8bb7d8d9436481bd0d4ad7775555ad1ac5040d84"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.x86_64-linux-musl.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "efff8e54bdb7c2450baaff6a044ea803407de2bd"
os = "freebsd"

    [[AzStorage.download]]
    sha256 = "ba537574f97eca464c5925525456d8afdd61f32cda42679553c37d66f6b99ff6"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "e2ed6903250028bf25d3829d74d0c2aad9d213ad"
os = "windows"

    [[AzStorage.download]]
    sha256 = "d75c975c4be4a6f260638f999973939ea9edc8846565ded8413cb45f87ea5c56"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.9.0+2/AzStorage.v0.9.0.x86_64-w64-mingw32.tar.gz"
