[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "6866cf805aef267d7da5903b77f6199b08fca4a9"
os = "macos"

    [[AzStorage.download]]
    sha256 = "3baa92d0f93d314f8d5203f50b68dd7fa362884eead8301fba22606089fe4cf3"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.aarch64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "96e558a0c14aaded9f6c62c61a1876a402f92cba"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "1ac010a903e272bbbe6bfa931331a554b5e9df4db7883b4d08a978a78f237bdb"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.aarch64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "4a0b1bc9a7323756356728725b9458d55526503e"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "6ae8242a8f03e9f37da3c8185da683cf3e7e4c42811760c29eedd8a53bbfc152"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.aarch64-linux-musl.tar.gz"
[[AzStorage]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5be9c3b6bacd3e061542b59eb47be9d2b1f3dd66"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "8d6c14756a221c6e4b55c8c1cd5f0b36f47070fa9ecc00012cafc197ff21d4f5"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.armv6l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "49eafd463607ec4b0765fbb6a19e3ae51f9c0027"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "2a78bb8627c659419aaa6b86ff07e8ac722598085fd374f711069445659aa3a5"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.armv6l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "040079bcfcd52dd67e1ee80ebb13eadc8159f473"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "277633738a8ce16667d86e1fdf371406b688cc96236f0d87629e7c950eff7ce5"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7f176d7b70f367b0e7d672ed7689dc21a76be720"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "497677d3a2e1c77e20f622285c06130acc93a936f4759363c7919f26831f0c5d"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.armv7l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "4228b455f6ee07ff764377128e1a9b0550bf3ede"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "f27d66d51d33b5451b62f38fab0954ffe243e4bb8edf641c373959f7fa074073"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.i686-linux-gnu.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "4449ed0187281fc993ff978b09494ee4560ed2a8"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "c2a88297254638ecbc0b1068ed34be2a01edd00c7aa2e72b0d3616a9de9ef846"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.i686-linux-musl.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "08842a869dc0538810b393832da831457334ec1e"
os = "windows"

    [[AzStorage.download]]
    sha256 = "f6f4cb96497f5a3bac8b75bc54b9827d104c234d7222f20918c9b531386321a9"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.i686-w64-mingw32.tar.gz"
[[AzStorage]]
arch = "powerpc64le"
git-tree-sha1 = "a27fed9973fbdd77d124406b510b57f4570319f7"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "ca1d8941c897abaddd5b0b958ceaa1692a0daaee2f5a727245bb7ba8c449e3ab"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "606ab203f25b9859845419b94aa30ac0dac91b11"
os = "macos"

    [[AzStorage.download]]
    sha256 = "d0a15158b6a79a7c339dceeb7d82849cf10b8d2b79efc8d36fc0bda9619a9329"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.x86_64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "b8df6a74742dd10853e900b10afafcf0998a607c"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "b9d80c424055ff505a137f4c3badd16e326d2f59c05a0db7d27d87f5383c420c"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.x86_64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "382f7b50ca6de212d8570a361c38e05a5b1dc59d"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "4ca8173901742669e8bcd11a9b7e2a069ca24709f75c9df735ceae19c647b199"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.x86_64-linux-musl.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "027bb166feff4dd833f6929a79419cad7aad9fad"
os = "freebsd"

    [[AzStorage.download]]
    sha256 = "3d3916005a0d750932511a69ddc858756017fd292859b6443efacbe818ec463e"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.x86_64-unknown-freebsd.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "3a79619084cbea3739caf554d73277ea1b073fec"
os = "windows"

    [[AzStorage.download]]
    sha256 = "5125f37de09927b9a5e583d66bef8fa8a6fae866dc17d5219d64c39d18bfe14a"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.4.0+0/AzStorage.v0.4.0.x86_64-w64-mingw32.tar.gz"
