[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "ae8c0862c93cc5bb9069dc20a3cd032eb25318c9"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "076ebe5c96c944cde00f7423e5c827b63894d8f45ddec98e9834181825d49fae"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.aarch64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "37409feb1ba92c03a4b0e23d6d2446b7f1b508e0"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "dd53edb003ed770379431151ff460167200fec0cc4eca43981609a344f7bed38"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.aarch64-linux-musl.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e0608b7abe5360988be457beb730023becc032e"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "cec7413cc34a992d7976645cc97ae373fa84d4a1259e5dd8712e7428793ec02f"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "788f0625507ae07e6ebc6c2b9122762383e616bb"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "d0750e3db4f814c6a38c345c7ac1fdec7f649a5e312e3743aac91aca87fe492a"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "01d89e37879642489b34b5b1d3e5f3debaa6265d"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "7093046904530db3d7334b0f1253d9a855c29a294b342700de8b5a839d5f0950"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.i686-linux-gnu.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "2c48715645d7516561bdda3b23951f00b38a8297"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "5b19c843d0df091c8d0c42b362f7196c75619c008880175d247ba594878737af"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.i686-linux-musl.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "d4625ea0898a98e1ef44a0a5ecbae60bf04630f4"
os = "windows"

    [[AzStorage.download]]
    sha256 = "6d0cdefb3a0598cecc590305d5030c7e24cedae55f394012e7ede53492fb6b2d"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.i686-w64-mingw32.tar.gz"
[[AzStorage]]
arch = "powerpc64le"
git-tree-sha1 = "90ef17d8642e9cb91546f8b92e328faf42f2c6cd"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "600e57c213faf650b718bddc79ae915093a99934c754c82586e3cd429cf00d41"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "2b15078419dd1e129cca5ed0ad6a9318ecbd7627"
os = "macos"

    [[AzStorage.download]]
    sha256 = "41abafe2f2c01e9ec8eaa4c72758555c25d3af913614a19a0a347b69b814f96b"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.x86_64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "7e93b49864a1a38ea562b3e91899a291e40b6b76"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "5947789fef10197d48ae6a6072b48d8b70f08013604f7e2c31c7572a1056a4d8"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.x86_64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "f2b78c846b027074d367bc47064aedf8b55f6c9e"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "80cb857073b36a6c821618f3981c5f333f97980fae95b0768aa9025fc5aa824d"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.x86_64-linux-musl.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "98f0344cc5a4a8a44e532040788ef56585d1e36f"
os = "freebsd"

    [[AzStorage.download]]
    sha256 = "2d476284a9723f4da1c2dc4c8756b57b678e3c0d45d8f951e85b0601586e30f8"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "3183394362a15890d3c8aa0da3ff7cdecc9ea338"
os = "windows"

    [[AzStorage.download]]
    sha256 = "111d4281fb88c22625862132acb53c7f451f5de3370571996b97f9894a8d0780"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.0+1/AzStorage.v0.2.0.x86_64-w64-mingw32.tar.gz"
