[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "56d325e8c77c787add4dbde12113a753290260d4"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "b6a192745e0dd4ead7207049f20ac7c160e01d61d99cc12c7efbc6fc3547aef6"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.aarch64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "1b5f1d825839061d09b76c5c24a1c8f1d39d7a8e"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "440ceda9b6b693c5c3dfef4ac8881423b63764ca8742b904bfe1b2b9d585661f"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.aarch64-linux-musl.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4fc586799527555faf2f38749f56e869eb22a6ed"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "71c56e568086a5d81c969f4fcf907814b0125559abedba7159bdfa8d0dcdfdbb"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.armv7l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e24ab320ece62ff91fa037d70e504dcc540e4f23"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "af94927eaacc9c9ddec5098bd657f6c56f1c493c7988f887cb0c28fad5cd5d4c"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.armv7l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "57083bf74e85b66126d4e5044c7a336f0a384148"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "c607cdb98e927f192b78ed1ec5172d9df7da3fd085cd2c7376ab27d4a1181e29"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.i686-linux-gnu.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "8cd400a044775bd98c523dea9b5034798019213f"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "87f920d234127fa5d069c21a6dab8f52aa3ec36d5269620ecc465188076c34ae"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.i686-linux-musl.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "0906bed70095495f5eb7417047d613ecc44e6b15"
os = "windows"

    [[AzStorage.download]]
    sha256 = "4237427fc0c9413cc14d9e989a5776059b8b8d53631c81a278abdd92d9be5cef"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.i686-w64-mingw32.tar.gz"
[[AzStorage]]
arch = "powerpc64le"
git-tree-sha1 = "e52d38c87142c36333e291f2e67fa41ef7a885a9"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "2ee78deadd680d8bc49595cbcf5741aae1e5f5f15330f9de9d290863c793e201"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "c4b38eb20e08ee1b7e7862e6e054d4593f4bcdd2"
os = "macos"

    [[AzStorage.download]]
    sha256 = "602d592139deca2e610cac7223fc76c07fda64af8a2c00fda6d0239c15d1d642"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.x86_64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "2cd9221b7b141b5b5855cc48f6b6fd2cf938c741"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "5c121b56121f43c6eedacfa0abfd247508b5af2ac0b2f04b9162245d90caf7e8"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.x86_64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "106d2718a9a8f649a2b8d5381e1b813608ab8aa7"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "714c849e1ef289dc8bc8de42a2f0e2e68890c7e6953a0c3661b81009a55cf556"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.x86_64-linux-musl.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "edb8bf23be31d163819ad910b0d58acb491e500f"
os = "freebsd"

    [[AzStorage.download]]
    sha256 = "3b0c3106bf23e7d5585bd77ec0dd45695ad776fc9ed61c0f8ace4e2910d978c6"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.x86_64-unknown-freebsd.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "c93a4fb537f24836de7fd01af91bab15842f0fff"
os = "windows"

    [[AzStorage.download]]
    sha256 = "245fa7b4ac9403e5d91b3bcd1d175bf2891a1901edfa5f363f40e4127e462139"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.2.1+0/AzStorage.v0.2.1.x86_64-w64-mingw32.tar.gz"
