[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "e0c5b9104d4f893631cde50a5957d5da89809041"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "4153ca1f54e48e7576fb7decb8e005182c3cb2a8e7430cdbed9f926e9ee57d09"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.aarch64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "aarch64"
git-tree-sha1 = "098fb1be80bb856f99714c3a17285b0566ac6e88"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "158735701909c00bb404a2c5c96f4748a85e9f50c81ffc1ba38d49af8df7ba71"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.aarch64-linux-musl.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b1b9e33d4e8b6f29749fe0f635611e60302aa3d"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "6952d8a68e7b30a2d1f4c6d8cf6a4badc7271df2e60b861f1c6e6cb60174bc4b"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[AzStorage]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f35adceed126ced68bdb366504d133a6aea1aae1"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "3c1ac7f4b024c788729dbe22134e3b90848082a8c7cd327b3ab0a8dd65941e25"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.armv7l-linux-musleabihf.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "aa468355f7db8cc560809c9a2094e508d4daabdf"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "7d665aaf020f583c2cf384e4aa806736bbc965924a685b34da965f26014adf48"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.i686-linux-gnu.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "7a3df0634632a835f5c7cfa5086e76416f96f1ab"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "659ed392e6bb60a08a9b46754e5ea22a4110844d1fe55e5e1bdc374fd02e39e3"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.i686-linux-musl.tar.gz"
[[AzStorage]]
arch = "i686"
git-tree-sha1 = "4564310d10a1c0cb79b2c0758b5577465e8c2cd0"
os = "windows"

    [[AzStorage.download]]
    sha256 = "b49c1a777eecc88a62379e387682d00727ca4dd9ddd0a8f8396324934ac29fd9"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.i686-w64-mingw32.tar.gz"
[[AzStorage]]
arch = "powerpc64le"
git-tree-sha1 = "15efb3d34f1c27fcd270fe47c8f0446c99d4ff16"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "f274f2793aacf329db57c8685c6b00503129dbce667c1d50bf771ca03385f61c"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "143a0871c8b7f85ba74c72649813fc436e148c88"
os = "macos"

    [[AzStorage.download]]
    sha256 = "e94543681d3cb0683ce2a7c725c115b3e47e8d6bed823ca960c2663c3e73a1e5"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.x86_64-apple-darwin.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "210a1fe56d2c990b6a0306f342378f272bda664b"
libc = "glibc"
os = "linux"

    [[AzStorage.download]]
    sha256 = "773c35a7b5afa71f86b906d38041ed7a28d0830bb96dda059557a2c5a4100f33"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.x86_64-linux-gnu.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "6377f479f1a01349cf21f54194ef3e581ba28682"
libc = "musl"
os = "linux"

    [[AzStorage.download]]
    sha256 = "e51baae482f3e7a7ac9f75e0e9856d708d2a873528bc852eb4101b8ba56046e2"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.x86_64-linux-musl.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "5a3bac075621224d9376d3ec99485d2c89622cc7"
os = "freebsd"

    [[AzStorage.download]]
    sha256 = "a98a43c9e68b7b1ae51571dcebc619a6feae40b8e26ee3dd88ec7f9f3d31fda0"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[AzStorage]]
arch = "x86_64"
git-tree-sha1 = "654126b086e29d53be1034ca3ed08dfdc0ee751c"
os = "windows"

    [[AzStorage.download]]
    sha256 = "2b3c41ef8155e8586bf1de22339bdc6a9436fb2c337776778f20bd9af992efb5"
    url = "https://github.com/JuliaBinaryWrappers/AzStorage_jll.jl/releases/download/AzStorage-v0.3.0+0/AzStorage.v0.3.0.x86_64-w64-mingw32.tar.gz"
